let ais_common=(function(){'use strict';function httpRequest(options){let method=typeof options.method!=='undefined'?options.method:'GET',async=typeof options.async!=='undefined'?options.async:!0,url=typeof options.url!=='undefined'?options.url:'',type=typeof options.type!=='undefined'?options.type:'',data2=typeof options.data!=='undefined'?options.data:'',timeout=typeof options.timeout!=='undefined'?options.timeout:'',withCredentials=typeof options.withCredentials!=='undefined'?options.withCredentials:!1;if(typeof options.data!=='undefined'&&typeof options.data==='object'){var data=Object.entries(options.data).map(e=>e.join('=')).join('&');console.log(options.data);console.log(data)}else{var data=''}
    var x=function(){if(typeof XMLHttpRequest!=='undefined'){return new XMLHttpRequest()}
        var versions=["MSXML2.XmlHttp.6.0","MSXML2.XmlHttp.5.0","MSXML2.XmlHttp.4.0","MSXML2.XmlHttp.3.0","MSXML2.XmlHttp.2.0","Microsoft.XmlHttp"];var xhr;for(var i=0;i<versions.length;i++){try{xhr=new ActiveXObject(versions[i]);break}catch(e){}}
        return xhr};var request=x();return new Promise(function(resolve,reject){request.onreadystatechange=function(){if(request.readyState!==4)return;if(request.status>=200&&request.status<300){resolve(request)}else{reject({status:request.status,statusText:request.statusText})}};request.responseType=type;request.withCredentials=withCredentials;request.timeout=timeout;if(method=='POST'){request.open(method,url,async);request.setRequestHeader("Content-type","application/x-www-form-urlencoded");request.setRequestHeader("X-Requested-With","XMLHttpRequest");request.send(data)}else{if(typeof data!=='undefined'&&data!==null){url=data.length>0?url+'?'+data:url}
        request.open(method,url,async);request.setRequestHeader("X-Requested-With","XMLHttpRequest");request.send()}})};function ajax(options){console.log('jquery Ajax call')
    return httpRequest(options)}
    function request(options){httpRequest(options);ajax(options)}
    return{ajax:ajax,}})();let aisb_setup=(function(){'use strict';const plugin_dir="http://localhost/wpartificial/wp-content/plugins/ais_bot/";let config={url:plugin_dir+'ais_search.php',data:{},method:'POST',type:'text',}
    const loader=document.createElement('DIV');loader.setAttribute('class','ais-loader');const aisb100={filter_by:"product",post_type:["product"],tags:["product"],ais_se:!1,ais_title:!0,ais_content:!0,ais_excerpt:!0,result_view:'ais_grid',showImage:!0,titleOverImage:!0,bodyContent:!0,showTitle:!0,showTitleWord:60,showContent:!1,showContentWord:100,pagination:!0,minItem:4,position:'afterend',showConfigSection:!0,showPostTypeMenu:!0,showCart:!0,showLayoutSelector:!0,wooCommerce:!0,showCartTemplate:!0,addToCart:!0,cart:!0,price:!0,enableAiSearchBot:!0,aiWooCommerceBot:!0,aiPostsBot:!0,aiPagesBot:!0,aiTagsBot:!0,aiProductsBot:!0,aiKnowledgeBot:!0,aiCustomBot:!0,}
    function getObject(e){const group=document.querySelectorAll('.aisb-setting .ais_setup_step .ais-item');let result={};for(var i=0;i<group.length;i++){var type=group[i].dataset.action;var key=group[i].dataset.key;if(type==='text'){console.log(type);result[key]=group[i].value}
        if(type==='checkbox'){console.log(type);result[key]=group[i].checked==!0?1:0}
        if(type==='select'){console.log(type);result[key]=group[i].options[group[i].selectedIndex].value}
        if(type==='radio'){console.log(type);var radio=group[i].querySelector("input:checked");console.log(radio);result[key]=radio?radio.value:'1'}}
        console.log(group);console.log(result);return result}
    function step_one(e){const obj=getObject(e);const conf=Object.assign({},config,{data:{action:'ais_bot_install',ais_api:'ais_site_config',requestData:JSON.stringify(obj)},});ais_common.ajax(conf).then((response)=>{console.log(typeof response.responseText)
        console.log(response.responseText)
        var result=JSON.parse(response.responseText);if(typeof result.data.status==='number'&&result.data.status===1){active(1)}else{console.error('Something went wrong!!!')}})}
    function step_two(e){const obj=aisb100;console.log(aisb100)
        console.log(obj)
        const conf=Object.assign({},config,{data:{action:'ais_bot_install',ais_api:'ais_bot_init',requestData:JSON.stringify(obj)},});ais_common.ajax(conf).then((response)=>{var result=JSON.parse(response.responseText);if(typeof result.data.status==='number'&&result.data.status===1){active(2)}else{console.error('Something went wrong!!!')}})}
    function step_three(e){const obj=getObject(e);const conf=Object.assign({},config,{data:{action:'ais_bot_install',ais_api:'ais_bot_active',requestData:JSON.stringify(obj)},});ais_common.ajax(conf).then((response)=>{var result=JSON.parse(response.responseText);if(typeof result.data.status==='number'&&result.data.status===1){active(3);loader.style.display='none'}else{console.error('Something went wrong!!!')}})}
    function execute(){const next=document.querySelectorAll('.ais_sutup_btn');const prev=document.querySelectorAll('.ais_sutup_btn_prev');console.log(' ------ fron Inside code ----------')
        next.forEach(ele=>{ele.addEventListener('click',(e)=>{loader.style.display='block';ele.offsetParent.appendChild(loader);let set=parseInt(e.target.dataset.step);if(set===1){step_one(e)}
            if(set===2){step_two(e)}
            if(set===3){step_three(e)}})});prev.forEach(ele=>{console.log(ele);ele.addEventListener('click',(e)=>{let set=parseInt(e.target.dataset.step);active(set)})})}
    var active=(set)=>{if(set<3){var step=document.querySelectorAll('.ais_setup_step');var step_no=document.querySelectorAll('.ais_step_no');for(var x=0;x<step.length;x++){if(x===set){step[set].style.display='block'}else{step[x].style.display='none'}
        loader.style.display='none'}
        for(var x=0;x<step_no.length;x++){if(x<=set){step_no[x].classList.add('ais_ok')}else{step_no[x].classList.remove('ais_ok')}}}}
    return{execute:execute,}})();let aisb_adminjs=(function(){let cbTabs,cbTabs2;const loader=document.createElement('DIV');loader.setAttribute('class','ais-loader');function aisSaveAllActions(e){loader.style.display='block';console.log(e);console.log(e.target);console.log(e.target.offsetParent);console.log(e.target.parentElement);e.target.parentElement.appendChild(loader);const group=document.querySelectorAll('.ais-settings-group .cb-setting .ais-item');let result={};for(var i=0;i<group.length;i++){var type=group[i].dataset.action;var key=group[i].dataset.key;if(type==='text'){console.log(type);result[key]=group[i].value}
    if(type==='checkbox'){console.log(type);result[key]=group[i].checked==!0?1:0}
    if(type==='select'){console.log(type);result[key]=group[i].options[group[i].selectedIndex].value}
    if(type==='radio'){console.log(type);var radio=group[i].querySelector("input:checked");console.log(radio);result[key]=radio?radio.value:'1'}}
    console.log(group);console.log(result);sendRequest(result)}
    function sendRequest(data){const obj=data;const plugin_dir="http://localhost/wpartificial/wp-content/plugins/ais_bot/";let config={url:plugin_dir+'ais_search.php',data:{action:'ais_bot_install',ais_api:'ais_bot_settings',requestData:JSON.stringify(obj)},method:'POST',type:'text',}
        ais_common.ajax(config).then((response)=>{console.log(typeof response.responseText)
            console.log(response.responseText)
            var result=JSON.parse(response.responseText);if(typeof result.data.status==='number'&&result.data.status===1){loader.style.display='none'}else{console.error('Something went wrong!!!')}})}
    function send(url,data){var request;if(request){request.abort()}
        request=jQuery.ajax({url:url,type:"post",beforeSend:function(request){request.setRequestHeader("Authorization",'My Token55555555');request.setRequestHeader("X-CSRF-TOKEN",'My Token55555555')},data:{"data":data}});request.done(function(response,textStatus,jqXHR){console.log("Hooray, it worked!");console.log(textStatus);console.log(jqXHR);console.log(response)});request.fail(function(jqXHR,textStatus,errorThrown){console.error("The following error occurred: "+textStatus,errorThrown)});request.always(function(){})}
    function tabAction(activePaneId){const title=document.getElementById('cb-title');if(activePaneId==='#cbBotConfig'){console.log('Tab----- cbBotConfig');title.innerText="Configration "}else if(activePaneId==='#userSetting'){console.log('Tab----- userSetting');title.innerText="Users "}else if(activePaneId==='#clientsSetting'){title.innerText="Clients List"}else if(activePaneId==='#cbSetting'){title.innerText="Bot Configuration"}else if(activePaneId==='#cbTags'){title.innerText="Tags"}else if(activePaneId==='#cbKnowledgeBase'){title.innerText="Knowledge Base"}else{console.log('hhhhhhhhhhhhhhhhhhhhhhhhhhhh')}}
    function cbTabClicks(tabClickEvent){tabClickEvent.preventDefault();for(var i=0;i<cbTabs.length;i++){cbTabs[i].classList.remove("sidebar__menu-item--active")}
        for(var i=0;i<cbTabs2.length;i++){cbTabs2[i].classList.remove("sidebar__menu-item--active")}
        var clickedTab=tabClickEvent.currentTarget;clickedTab.classList.add("sidebar__menu-item--active");tabClickEvent.preventDefault();const myContentPanes=document.querySelectorAll(".cb-setting");for(i=0;i<myContentPanes.length;i++){myContentPanes[i].classList.remove("active")}
        var anchorReference=tabClickEvent.target;var activePaneId=anchorReference.getAttribute("data-id");var activePane=document.querySelector(activePaneId);activePane.classList.add("active");tabAction(activePaneId)}
    function tabExecute(){cbTabs=document.querySelectorAll("ul#cb-settings-actions > li");cbTabs2=document.querySelectorAll("ul#cb-settings-actions2 > li");for(var i=0;i<cbTabs.length;i++){cbTabs[i].addEventListener("click",cbTabClicks)}
        for(var i=0;i<cbTabs2.length;i++){cbTabs2[i].addEventListener("click",cbTabClicks)}
        console.log('------- ais_save ---------');const ais_save=document.querySelector("#ais-save-action-btn");console.log(ais_save);ais_save.addEventListener('click',aisSaveAllActions)}
    return{execute:tabExecute}})();(function(){'use strict';jQuery(document).ready(function(){if(!0){const action=['aisb_adminjs','aisb_setup'];console.log('------------------- querySelector -------------');const setting=document.querySelector('.aisb-setting');const setting_action=setting.dataset.action;console.log(setting);console.log(setting.dataset.action);if(setting_action!==''&&action.includes(setting_action)){if(setting_action==='aisb_setup'&&typeof aisb_setup==='object'){console.log('----------- aisb_setup -------- execute-------');aisb_setup.execute()}
    if(setting_action==='aisb_adminjs'&&typeof aisb_adminjs==='object'){console.log('----------- aisb_adminjs -------- execute-------');aisb_adminjs.execute()}}}})})()