//config file
// requirejs.config({
//     paths: {
//         // jquery: ['jquery.min'],
//         // fuse: 'fuse.min',
//         fuseSearch: 'fuseSearch',
//         eCommerce: 'eCommerce',
//         // test: 'test',
//         // conn: 'conn',
//         searchBot: 'searchBot',
//         // clientInfo: 'clientInfo',
//         // connServer: 'connServer',
//         // paginate: 'paginate',
//         // settings: 'settings',
//         // index: 'index',
//         // bot: 'bot',
//         // form: 'form',
//         help: 'help',
//         controller: 'controller',
//         // chatBot: 'chatBot',
//         // singleAction: 'singleBot',
//         actionBot: 'actionBot',
//         knowledgeBase: 'knowledgeBase',
//         // master: 'master',
//         // productsBot: 'productsBot',
//         // postsBot: 'postsBot',
//         // pagesBot: 'pagesBot',
//         // tagsBot: 'tagsBot',
//         customBot: 'customBot',
//         axios: 'axios.min',
//         // crypto: 'crypto',
//         template: 'template',
//         elasticlunr: 'elasticlunr',
//         searchEngine: 'searchEngine',
//         // slider: 'slider',
//         // carousel: 'carousel',
//         pagination: 'pagination',
//         jsCookie: 'jsCookie',
//         // fileSaver: 'FileSaver',
//         // multiselect: 'multiselect',
//         // woocommerce: 'productBot'
//     },
//     baseUrl: 'botjs'
// });
